
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% This code invert ETAS parameter from the simulation result 
% generated by RUN_ETAS_Simulation.m.
%
% This code only contains essentials for maximum likely hood inversion 
% to enhance readability. Inversion can be slow if data size is large
% The code is generated for following research:
% Im and Avouac (202?), Cascading Foreshocks, Aftershocks, and Earthquake 
% Swarms in a Discrete Fault Network, GJI
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%


clear all

load CatalogETAS

global Day_ThisInversion
global Magnitude_ThisInversion
global M_0_ThisInversion

[Day,sortIdx] = sort(Day);
Magnitude = Magnitude(sortIdx);

Day_ThisInversion = Day;
Magnitude_ThisInversion = Magnitude;
M_0_ThisInversion = M0_Original;

figure(1)
scatter(Day, Magnitude)

fun = @Function_LogLikelyhoodNegative

% Initial Guess 
Mu = 0.001;
C = 1e-3;
P = 1.1;
K0 = 0.001;
Alpha = log(10)*0.5;
ThetaLowerBound = [0.0, 0.0, 0.0, 0.0, 0.0];
ThetaUpperBound = [1.0, 1.0, 2.0, 0.1, 5.0];

Theta = [Mu, C, P, K0, Alpha];

ThetaInitialGuess= Theta;


%%%%%%% fminsearch - This does the job but unstable. 
Theta_Inverted = fminsearch(fun,Theta);


%%%%%%%%%% fminsearchbnd - This is stabler (no negative allowed). Download at 
%%%%% https://www.mathworks.com/matlabcentral/fileexchange/8277-fminsearchbnd-fminsearchcon 
%Theta_Inverted = fminsearchbnd(fun,Theta, ThetaLowerBound, ThetaUpperBound);



ThetaInitialGuess
ThetaOriginal
Theta_Inverted








%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%  Function  %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%% Below function calculates the maximum likelihood %%%%%%%%%%%%

function [LLValueNegative] = Function_LogLikelyhoodNegative(Theta)

global Day_ThisInversion
global Magnitude_ThisInversion 
global M_0_ThisInversion

Day=Day_ThisInversion;
Magnitude=Magnitude_ThisInversion;
M_0 = M_0_ThisInversion;

MaxDay = Day(end);
TotalEventCount = length(Day);

Mu = Theta(1);
C = Theta(2);
P = Theta(3);
K0 = Theta(4);
Alpha = Theta(5);

SumTerm = 0.0;
IntegralTerm=0.0;
IntegralTerm = IntegralTerm + Mu * MaxDay;
    for i=1:TotalEventCount
        
        % Integral Term of equation 23 of Ogata (1988)
        IntegralTerm = IntegralTerm + K0*exp(Alpha*(Magnitude(i)-M_0)) * ...
        (((C + MaxDay - Day(i))^(1-P))/(1-P) - (C^(1-P))/(1-P));
        
        % Summation Term of equation 23 of Ogata (1988)
        SumTerm_i = 0.0;
        SumTerm_i = SumTerm_i + Mu;
        if i>1
            for j=1:i-1
                if Day(i)>Day(j) 
                SumTerm_i = SumTerm_i + K0*exp(Alpha*(Magnitude(j)-M_0))/((Day(i)-Day(j)+C)^P);
                end
            end    
        end
        SumTerm=SumTerm+log(SumTerm_i);

    end
    
    LLValueNegative = -1 * (SumTerm - IntegralTerm); % multiply -1 to use 'fminsearch' function 

%     [LLValueNegative]
    [Theta]

end
